import {
  Tool, BRUSH_SIZES,
  GRID_W, GRID_H, CELL_PX,
  type BrushSize, type WorkerInput, type FrameMessage, type StateSnapshotMessage,
} from './types';

// ─── Fun toggles ────────────────────────────────────────────────
type WindState = 0 | 1 | -1 | 2;
let windState: WindState = 0;
let gravityReversed = false;
import { encodeGifBlob, type GifFrameData } from './gif-encoder';
import { SCENES } from './scenes';

// ─── Canvas setup ────────────────────────────────────────────────
const canvas = document.getElementById('sim-canvas') as HTMLCanvasElement;
const ctx = canvas.getContext('2d')!;

const CANVAS_W = GRID_W * CELL_PX;
const CANVAS_H = GRID_H * CELL_PX;
canvas.width = CANVAS_W;
canvas.height = CANVAS_H;
// CSS handles display sizing via aspect-ratio + width:100%

// ─── Spawn the Web Worker ──────────────────────────────────────
const worker = new Worker(
  new URL('./worker/sim.worker.ts', import.meta.url),
  { type: 'module' },
);

worker.postMessage({ type: 'init', width: GRID_W, height: GRID_H } satisfies WorkerInput);

// ─── Input state ────────────────────────────────────────────────
let mouseDown = false;
let tool = Tool.SAND;
let brushSize: BrushSize = 3;
let lastX = -1;
let lastY = -1;

// ─── Canvas state tracking ─────────────────────────────────────
type CanvasState = 'fresh' | 'autoGenerated' | 'userModified';
let canvasState: CanvasState = 'fresh';

function markUserModified() {
  if (canvasState === 'fresh' || canvasState === 'autoGenerated') {
    canvasState = 'userModified';
  }
}

// ─── Keyboard shortcuts ─────────────────────────────────────────
const toolByKey: Record<string, Tool> = {
  '1': Tool.SAND, '2': Tool.WATER, '3': Tool.FIRE,
  '4': Tool.WALL, '5': Tool.WOOD, '6': Tool.OIL,
  '7': Tool.PLANT, '8': Tool.LAVA, '9': Tool.ACID,
  '0': Tool.ERASER, 'e': Tool.EXPLOSIVE,
};

document.addEventListener('keydown', (e) => {
  const key = e.key;
  if (key in toolByKey) {
    selectTool(toolByKey[key]);
    e.preventDefault();
    return;
  }
  if (key === '-' || key === '_') {
    cycleBrush(-1);
    e.preventDefault();
  }
  if (key === '=' || key === '+') {
    cycleBrush(1);
    e.preventDefault();
  }
  if (key.toLowerCase() === 'c' && !e.ctrlKey && !e.metaKey) {
    worker.postMessage({ type: 'clear' } satisfies WorkerInput);
    clearCanvas();
    latestFrame = null;
    canvasState = 'fresh';
    e.preventDefault();
  }
  if (key.toLowerCase() === 'g') {
    toggleRecording();
    e.preventDefault();
  }
  // Ctrl+S = save, Ctrl+O = load
  if ((e.ctrlKey || e.metaKey) && key.toLowerCase() === 's') {
    e.preventDefault();
    saveToFile();
  }
  if ((e.ctrlKey || e.metaKey) && key.toLowerCase() === 'o') {
    e.preventDefault();
    (document.getElementById('load-input') as HTMLInputElement).click();
  }
});

// ─── Coordinate helpers ─────────────────────────────────────────
function canvasToGrid(cx: number, cy: number): [number, number] {
  const rect = canvas.getBoundingClientRect();
  const scaleX = canvas.width / rect.width;
  const scaleY = canvas.height / rect.height;
  const gx = Math.floor((cx - rect.left) * scaleX / CELL_PX);
  const gy = Math.floor((cy - rect.top) * scaleY / CELL_PX);
  return [gx, gy];
}

function sendInput(x: number, y: number, active: boolean) {
  if (active) markUserModified();
  worker.postMessage({
    type: 'input',
    x, y, tool, brushSize, active,
  } satisfies WorkerInput);
}

// ─── Mouse / touch handlers ─────────────────────────────────────
function onPointerDown(cx: number, cy: number) {
  mouseDown = true;
  const [gx, gy] = canvasToGrid(cx, cy);
  lastX = gx; lastY = gy;
  if (tool === Tool.EXPLOSIVE) {
    mouseDown = false; // single click, no drag
    const radius = brushSize * 3 + 4;
    worker.postMessage({ type: 'explode', x: gx, y: gy, radius } satisfies WorkerInput);
    return;
  }
  sendInput(gx, gy, true);
}

function onPointerMove(cx: number, cy: number) {
  const [gx, gy] = canvasToGrid(cx, cy);
  if (gx !== lastX || gy !== lastY || mouseDown) {
    lastX = gx; lastY = gy;
    if (mouseDown) sendInput(gx, gy, true);
  }
  updateModeIndicator(cx, cy);
}

function onPointerUp() {
  if (!mouseDown) return;
  mouseDown = false;
  // Post input with active=false on next microtask to let in-progress ticks finish
  setTimeout(() => sendInput(-1, -1, false), 0);
}

// Mouse
canvas.addEventListener('mousedown', (e) => onPointerDown(e.clientX, e.clientY));
canvas.addEventListener('mousemove', (e) => onPointerMove(e.clientX, e.clientY));
canvas.addEventListener('mouseup', () => onPointerUp());
canvas.addEventListener('mouseleave', () => onPointerUp());

// Touch
canvas.addEventListener('touchstart', (e) => {
  e.preventDefault();
  const t = e.touches[0];
  onPointerDown(t.clientX, t.clientY);
}, { passive: false });
canvas.addEventListener('touchmove', (e) => {
  e.preventDefault();
  const t = e.touches[0];
  onPointerMove(t.clientX, t.clientY);
}, { passive: false });
canvas.addEventListener('touchend', (e) => {
  e.preventDefault();
  onPointerUp();
}, { passive: false });

// ─── Tool palette ────────────────────────────────────────────────
const toolButtons: Record<string, Tool> = {
  'tool-sand': Tool.SAND,
  'tool-water': Tool.WATER,
  'tool-fire': Tool.FIRE,
  'tool-wall': Tool.WALL,
  'tool-wood': Tool.WOOD,
  'tool-oil': Tool.OIL,
  'tool-plant': Tool.PLANT,
  'tool-lava': Tool.LAVA,
  'tool-acid': Tool.ACID,
  'tool-eraser': Tool.ERASER,
  'tool-explode': Tool.EXPLOSIVE,
};

const toolNames: Record<Tool, string> = {
  [Tool.SAND]: 'Sand',
  [Tool.WATER]: 'Water',
  [Tool.FIRE]: 'Fire',
  [Tool.WALL]: 'Wall',
  [Tool.WOOD]: 'Wood',
  [Tool.OIL]: 'Oil',
  [Tool.PLANT]: 'Plant',
  [Tool.LAVA]: 'Lava',
  [Tool.ACID]: 'Acid',
  [Tool.ERASER]: 'Eraser',
  [Tool.EXPLOSIVE]: 'Explode',
};

let activeToolBtn: HTMLElement | null = null;
const statusTool = document.getElementById('status-tool')!;

function selectTool(t: Tool) {
  tool = t;
  statusTool.textContent = toolNames[t];
  if (activeToolBtn) activeToolBtn.classList.remove('active');

  // Find button by matching tool
  for (const [id, tVal] of Object.entries(toolButtons)) {
    if (tVal === t) {
      const btn = document.getElementById(id);
      if (btn) {
        btn.classList.add('active');
        activeToolBtn = btn;
      }
      break;
    }
  }
}

for (const [id, t] of Object.entries(toolButtons)) {
  const btn = document.getElementById(id);
  if (!btn) continue;
  btn.addEventListener('click', () => selectTool(t));
  // Also handle on touchend to avoid double-firing
  btn.addEventListener('touchend', (e) => { e.preventDefault(); selectTool(t); });
}

// ─── Brush size ──────────────────────────────────────────────────
const brushDisplay = document.getElementById('brush-size-display')!;
const statusSize = document.getElementById('status-size')!;
const brushDecrease = document.getElementById('brush-decrease')!;
const brushIncrease = document.getElementById('brush-increase')!;

function updateBrushDisplay() {
  brushDisplay.textContent = String(brushSize);
  statusSize.textContent = String(brushSize);
}

function cycleBrush(dir: number) {
  const idx = BRUSH_SIZES.indexOf(brushSize);
  const next = idx + dir;
  if (next >= 0 && next < BRUSH_SIZES.length) {
    brushSize = BRUSH_SIZES[next];
    updateBrushDisplay();
  }
}

brushDecrease.addEventListener('click', () => cycleBrush(-1));
brushIncrease.addEventListener('click', () => cycleBrush(1));

// ─── Clear button ────────────────────────────────────────────────
document.getElementById('btn-clear')!.addEventListener('click', () => {
  worker.postMessage({ type: 'clear' } satisfies WorkerInput);
  clearCanvas();
  latestFrame = null;
  canvasState = 'fresh';
});

// ─── Brush indicator (icon follows mouse near cursor) ─────────
const brushIcon: Record<Tool, string> = {
  [Tool.SAND]: '🟤',
  [Tool.WATER]: '💧',
  [Tool.FIRE]: '🔥',
  [Tool.WALL]: '🧱',
  [Tool.WOOD]: '🪵',
  [Tool.OIL]: '🛢️',
  [Tool.PLANT]: '🌿',
  [Tool.LAVA]: '🌋',
  [Tool.ACID]: '🧪',
  [Tool.ERASER]: '🧹',
  [Tool.EXPLOSIVE]: '💥',
};

const modeIndicator = document.getElementById('mode-indicator')!;
let indicatorPending = false;
let indicatorX = 0, indicatorY = 0;
function updateModeIndicator(cx: number, cy: number) {
  indicatorX = cx; indicatorY = cy; // always store latest position
  if (indicatorPending) return;
  indicatorPending = true;
  requestAnimationFrame(() => {
    indicatorPending = false;
    const icon = brushIcon[tool] || '';
    if (!icon) {
      modeIndicator.style.display = 'none';
      return;
    }
    modeIndicator.textContent = icon;
    modeIndicator.style.display = 'block';
    modeIndicator.style.left = (indicatorX + 16) + 'px';
    modeIndicator.style.top = (indicatorY - 24) + 'px';
  });
}

// Hide indicator on mouse leave
canvas.addEventListener('mouseleave', () => { modeIndicator.style.display = 'none'; });

// ─── Status bar mode indicators ──────────────────────────────
const statusModes = document.createElement('span');
statusModes.className = 'status-badge';
statusModes.style.cssText = 'color:#7c5cbf;display:none;font-size:0.65rem;gap:2px';
statusModes.textContent = '';
document.querySelector('.status')?.appendChild(statusModes);

function updateStatusModes() {
  const parts: string[] = [];
  if (gravityReversed) parts.push('🔄↑');
  if (windState === 1) parts.push('🌬️→');
  else if (windState === -1) parts.push('🌬️←');
  else if (windState === 2) parts.push('🌬️🎲');
  if (parts.length) {
    statusModes.textContent = parts.join(' ');
    statusModes.style.display = 'inline';
  } else {
    statusModes.style.display = 'none';
  }
}

// ─── Fun buttons: Wind, Gravity ───────────────────────────────
const btnWind = document.getElementById('btn-wind')!;
const btnGravity = document.getElementById('btn-gravity')!;

// Wind labels: arrow points where wind blows TO
const windLabels = ['🌬️', '🌬️ →', '🌬️ ←', '🌬️ 🎲'];
const windStates: WindState[] = [0, 1, -1, 2];
function cycleWind() {
  const idx = windStates.indexOf(windState);
  const next = (idx + 1) % windStates.length;
  windState = windStates[next];
  worker.postMessage({ type: 'wind', direction: windState } satisfies WorkerInput);
  btnWind.textContent = windLabels[next];
  updateStatusModes();
}
btnWind.addEventListener('click', cycleWind);

btnGravity.addEventListener('click', () => {
  gravityReversed = !gravityReversed;
  const dir = gravityReversed ? -1 : 1;
  worker.postMessage({ type: 'gravity', direction: dir } satisfies WorkerInput);
  btnGravity.textContent = gravityReversed ? '🔄 ↑' : '🔄 ↓';
  updateStatusModes();
});

// Keyboard shortcuts
document.addEventListener('keydown', (e) => {
  if (e.key.toLowerCase() === 'w' && !e.ctrlKey && !e.metaKey) {
    cycleWind();
    e.preventDefault();
  }
});

// ─── Save / Load buttons ───────────────────────────────────────
document.getElementById('btn-save')!.addEventListener('click', saveToFile);
const loadInput = document.getElementById('load-input') as HTMLInputElement;
document.getElementById('btn-load')!.addEventListener('click', () => loadInput.click());
loadInput.addEventListener('change', (e) => {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (file) loadFromFile(file);
  loadInput.value = ''; // allow re-selecting same file
});

// Try restoring autosave on init
let autosaveRestored = false;
const autosaveHandler = () => {
  if (!autosaveRestored) {
    autosaveRestored = true;
    setTimeout(tryRestoreAutosave, 100);
  }
};
// Hook into first frame to restore autosave after worker is ready
worker.addEventListener('message', autosaveHandler, { once: true });

// ─── Scene Generation ───────────────────────────────────────────
let currentSceneIndex = 0;
let lastSceneIndex: number | null = null;
const generateBtn = document.getElementById('btn-generate')!;
const confirmOverlay = document.getElementById('confirm-overlay')!;
const confirmBtn = document.getElementById('confirm-yes')!;
const cancelBtn = document.getElementById('confirm-no')!;
const sceneNameEl = document.getElementById('scene-name')!;
let sceneToastTimer: ReturnType<typeof setTimeout> | null = null;

function showSceneToast(index: number) {
  const scene = SCENES[index];
  const total = SCENES.length;
  sceneNameEl.innerHTML = `<span style="font-size:0.85rem">${scene.emoji}</span> <strong>${scene.name}</strong>  <span style="color:#999;font-size:0.6rem">${index + 1}/${total}</span><br><span style="font-size:0.6rem;color:#aaa">${scene.description}</span>`;
  sceneNameEl.classList.add('visible');
  if (sceneToastTimer) clearTimeout(sceneToastTimer);
  sceneToastTimer = setTimeout(() => {
    sceneNameEl.classList.remove('visible');
  }, 4500);
}

function randomSceneIndexExcluding(previous: number | null): number {
  if (SCENES.length <= 1) return 0;
  let idx: number;
  do {
    idx = Math.floor(Math.random() * SCENES.length);
  } while (idx === previous);
  return idx;
}

/** Clear the canvas visually (immediately, synchronous). */
function clearCanvas() {
  // Fill the displayed canvas with background gradient
  for (let y = 0; y < GRID_H; y++) {
    const t = y / (GRID_H - 1);
    const bgR = 20 - t * 8;
    const bgG = 15 + t * 10;
    const bgB = 25 + t * 8;
    for (let x = 0; x < GRID_W; x++) {
      const pi = (y * GRID_W + x) * 4;
      gridImgData.data[pi] = bgR;
      gridImgData.data[pi + 1] = bgG;
      gridImgData.data[pi + 2] = bgB;
      gridImgData.data[pi + 3] = 255;
    }
  }
  offCtx.putImageData(gridImgData, 0, 0);
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(offscreen, 0, 0, CANVAS_W, CANVAS_H);
}

function generateScene(sceneIndex?: number) {
  if (sceneGenerating) return; // debounce: ignore rapid clicks
  sceneGenerating = true;

  const seed = Date.now() ^ (Math.random() * 0x7fffffff | 0);
  if (sceneIndex === undefined) {
    sceneIndex = randomSceneIndexExcluding(lastSceneIndex);
  }
  lastSceneIndex = sceneIndex;
  currentSceneIndex = sceneIndex;

  // Scene transition flash
  const canvasWrap = document.querySelector('.canvas-wrap')!;
  canvasWrap.classList.add('scene-transition');
  setTimeout(() => canvasWrap.classList.remove('scene-transition'), 350);

  // ⭐ Immediately clear the canvas so user sees instant feedback,
  // before the worker even starts its CPU-heavy scene generation.
  worker.postMessage({ type: 'clear' } satisfies WorkerInput);
  clearCanvas();
  latestFrame = null;

  // Generate the scene in the worker (off the main thread)
  const genToken = ++sceneGenCounter;
  pendingGenToken = genToken;
  worker.postMessage({ type: 'generateScene', sceneIndex, seed, genToken } satisfies WorkerInput);

  canvasState = 'autoGenerated';
  showSceneToast(sceneIndex);

  // Randomize wind for each new scene (more fun)
  const randomWind = windStates[Math.floor(Math.random() * windStates.length)];
  windState = randomWind;
  worker.postMessage({ type: 'wind', direction: windState } satisfies WorkerInput);
  const windIdx = windStates.indexOf(windState);
  btnWind.textContent = windLabels[windIdx];
  updateStatusModes();
}

function showConfirm() {
  confirmOverlay.classList.add('visible');
}
function hideConfirm() {
  confirmOverlay.classList.remove('visible');
}

generateBtn.addEventListener('click', () => {
  if (canvasState === 'userModified') {
    showConfirm();
  } else {
    generateScene();
  }
});
confirmBtn.addEventListener('click', () => {
  hideConfirm();
  generateScene();
});
cancelBtn.addEventListener('click', hideConfirm);
confirmOverlay.addEventListener('click', (e) => {
  if (e.target === confirmOverlay) hideConfirm();
});

// Keyboard: 'N' for new scene, left/right arrows to cycle
document.addEventListener('keydown', (e) => {
  if (e.key.toLowerCase() === 'n' && !e.ctrlKey && !e.metaKey && !e.repeat) {
    if (canvasState === 'userModified') {
      showConfirm();
    } else {
      generateScene();
    }
    e.preventDefault();
  }
  if ((e.key === 'ArrowRight' || e.key === 'ArrowLeft') && !e.ctrlKey && !e.metaKey && !e.repeat) {
    if (canvasState === 'userModified') {
      showConfirm();
      return;
    }
    const dir = e.key === 'ArrowRight' ? 1 : -1;
    const next = ((currentSceneIndex + dir) % SCENES.length + SCENES.length) % SCENES.length;
    generateScene(next);
    e.preventDefault();
  }
});

// ─── GIF Recording ──────────────────────────────────────────────
let recording = false;
let recordedFrames: Uint8Array[] = [];
let recordingFrameCount = 0;
const RECORD_DURATION_MS = 3000;      // 3 seconds
const RECORD_TOTAL_FRAMES = 90;       // ~30 fps target

const btnRecord = document.getElementById('btn-record')!;

function toggleRecording() {
  if (recording) {
    // Already recording — click again to stop early
    recording = false;
    const captured = recordedFrames;
    recordedFrames = [];
    if (captured.length < 5) {
      btnRecord.textContent = '🎬 GIF';
      btnRecord.classList.remove('active');
      return;
    }
    encodeGIF(captured);
    return;
  }
  // Start recording
  recording = true;
  recordingFrameCount = 0;
  recordedFrames = [];
  btnRecord.textContent = '⏺ Rec...';
  btnRecord.classList.add('active');
}

btnRecord.addEventListener('click', toggleRecording);

async function encodeGIF(frames: Uint8Array[]) {
  btnRecord.textContent = '⏳ 0%';
  btnRecord.classList.remove('active');

  const totalFrames = frames.length;
  const delayMs = Math.round(RECORD_DURATION_MS / totalFrames);

  // Process in batches, yielding to UI between batches
  const frameDatas: GifFrameData[] = [];
  const BATCH = 10;

  for (let i = 0; i < totalFrames; i++) {
    frameDatas.push({ pixels: frames[i], delay: delayMs });

    if (frameDatas.length >= BATCH || i === totalFrames - 1) {
      // Yield to UI before encoding
      await new Promise(r => setTimeout(r, 0));
    }
  }

  btnRecord.textContent = '⏳ Encoding...';

  try {
    const blob = await encodeGifBlob(frameDatas);

    // Download
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `powderbox-${Date.now()}.gif`;
    a.click();
    URL.revokeObjectURL(url);
  } catch (err) {
    console.error('GIF encoding failed:', err);
  }

  btnRecord.textContent = '🎬 GIF';
}

// ─── GPU-accelerated pixel rendering ───────────────────────────
const offscreen = new OffscreenCanvas(GRID_W, GRID_H);
const offCtx = offscreen.getContext('2d')!;
const gridImgData = offCtx.createImageData(GRID_W, GRID_H);
let paused = false;
const pauseOverlay = document.createElement('div');
pauseOverlay.style.cssText = `
  position:absolute;inset:0;display:flex;align-items:center;justify-content:center;
  background:rgba(0,0,0,0.5);color:#f7c948;font-size:2rem;font-weight:700;
  letter-spacing:0.1em;pointer-events:none;opacity:0;transition:opacity 0.2s;
  border-radius:10px;z-index:10;
`;
pauseOverlay.textContent = '⏸ PAUSED';
document.querySelector('.canvas-wrap')?.appendChild(pauseOverlay);

const statusPause = document.createElement('span');
statusPause.className = 'status-badge';
statusPause.style.cssText = 'color:#f7c948;display:none';
statusPause.textContent = '⏸ PAUSED';
document.querySelector('.status')?.appendChild(statusPause);

function updatePauseUI() {
  pauseOverlay.style.opacity = paused ? '1' : '0';
  statusPause.style.display = paused ? 'inline' : 'none';
}

// Space to pause
document.addEventListener('keydown', (e) => {
  if (e.key === ' ' || e.key === 'Space') {
    e.preventDefault();
    const wasPaused = paused;
    paused = !paused;
    updatePauseUI();
    // Resume ticking when unpaused
    if (wasPaused && renderLoopRunning) queueTick();
  }
});

// ─── rAF-throttled render loop ──────────────────────────────────
// Decouples rendering from worker tick rate. The worker runs
// independently and only one tick is ever pending. At vsync (60fps),
// we grab the latest frame and render it. This prevents flooding
// the main thread when the worker processes ticks faster than
// the display can refresh.
let latestFrame: Uint8ClampedArray | null = null;
let tickPending = false;
let renderLoopRunning = false;
let sceneGenerating = false; // debounce: ignore generate clicks while worker is busy
let sceneGenCounter = 0;      // incremented on each generateScene call
let pendingGenToken = 0;      // expected genToken to reset sceneGenerating

function queueTick() {
  if (tickPending) return;
  tickPending = true;
  worker.postMessage({ type: 'tick' } satisfies WorkerInput);
}

function renderTick() {
  if (!latestFrame) return;
  const src = latestFrame;
  latestFrame = null;

  gridImgData.data.set(src);
  offCtx.putImageData(gridImgData, 0, 0);
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(offscreen, 0, 0, CANVAS_W, CANVAS_H);

  // Request next tick only after rendering (backpressure)
  if (!paused) queueTick();
}

function renderLoop(_time: number) {
  if (!paused) renderTick();
  requestAnimationFrame(renderLoop);
}

worker.onmessage = (e: MessageEvent<FrameMessage | StateSnapshotMessage>) => {
  const msg = e.data;
  if (msg.type === 'stateSnapshot') {
    if (pendingSaveResolve) {
      pendingSaveResolve(msg.data);
      pendingSaveResolve = null;
    }
    return;
  }
  if (msg.type !== 'frame') return;

  const src = msg.pixels;
  tickPending = false;

  // GIF recording: capture raw RGBA frame at grid resolution
  if (recording) {
    recordedFrames.push(new Uint8Array(src));
    recordingFrameCount++;
    btnRecord.textContent = `⏺ ${Math.round(recordingFrameCount / RECORD_TOTAL_FRAMES * 100)}%`;

    if (recordingFrameCount >= RECORD_TOTAL_FRAMES) {
      recording = false;
      const capturedFrames = recordedFrames;
      recordedFrames = [];
      encodeGIF(capturedFrames);
      return; // don't render this frame, let encoding happen
    }
  }

  // Store the latest frame for the rAF render loop
  // If we already have a pending frame, it gets replaced so we only
  // render the most recent one (drops intermediate frames at high tick rates).
  latestFrame = src;
  // Only reset the scene generation debounce when the frame WITH the
  // matching genToken arrives.  Stale tick frames from before the
  // generateScene call do NOT reset sceneGenerating.
  if (msg.sceneGenToken === pendingGenToken) {
    sceneGenerating = false;
  }

  // Start rAF loop on first frame
  if (!renderLoopRunning) {
    renderLoopRunning = true;
    requestAnimationFrame(renderLoop);
  }
};

// ─── Save / Load ────────────────────────────────────────────────
const PBOX_MAGIC = 0x50424F58; // 'PBOX' as uint32 LE
let pendingSaveResolve: ((data: ArrayBuffer) => void) | null = null;

function saveToFile() {
  // Request state from worker
  worker.postMessage({ type: 'saveState' } satisfies WorkerInput);
  pendingSaveResolve = (data: ArrayBuffer) => {
    const gridArr = new Uint8Array(data);
    const fileBuf = new ArrayBuffer(8 + data.byteLength);
    const fw = new DataView(fileBuf);
    fw.setUint32(0, PBOX_MAGIC, true);       // magic
    fw.setUint16(4, GRID_W, true);             // width
    fw.setUint16(6, GRID_H, true);             // height
    new Uint8Array(fileBuf, 8).set(gridArr);    // grid + life

    const blob = new Blob([fileBuf], { type: 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `powderbox-${Date.now()}.pbox`;
    a.click();
    URL.revokeObjectURL(url);
  };
}

function loadFromFile(file: File) {
  const reader = new FileReader();
  reader.onload = () => {
    const buf = reader.result as ArrayBuffer;
    const view = new DataView(buf);
    const magic = view.getUint32(0, true);
    if (magic !== PBOX_MAGIC) {
      alert('Not a valid PowderBox save (.pbox) file.');
      return;
    }
    const w = view.getUint16(4, true);
    const h = view.getUint16(6, true);
    if (w !== GRID_W || h !== GRID_H) {
      alert(`Save file has wrong dimensions (${w}×${h}), expected ${GRID_W}×${GRID_H}.`);
      return;
    }
    const payload = buf.slice(8);
    worker.postMessage({ type: 'loadState', data: payload }, [payload]);
    canvasState = 'userModified';
  };
  reader.readAsArrayBuffer(file);
}

// ─── Auto-save to localStorage ─────────────────────────────────
function autoSave() {
  worker.postMessage({ type: 'saveState' } satisfies WorkerInput);
  pendingSaveResolve = (data: ArrayBuffer) => {
    try {
      const bytes = new Uint8Array(data);
      const b64 = btoa(String.fromCharCode(...bytes));
      localStorage.setItem('powderbox_autosave', b64);
    } catch { /* quota exceeded, ignore */ }
  };
}

// Auto-save every 10 seconds while not paused
setInterval(() => {
  if (!paused) autoSave();
}, 10000);

// Restore autosave on load (after worker init)
function tryRestoreAutosave() {
  const b64 = localStorage.getItem('powderbox_autosave');
  if (!b64) return;
  try {
    const bytes = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
    if (bytes.length !== GRID_W * GRID_H * 2) return;
    // Prepend dimensions so the worker's loadState handler can verify
    const meta = new ArrayBuffer(4);
    const mv = new DataView(meta);
    mv.setUint16(0, GRID_W, true);
    mv.setUint16(2, GRID_H, true);
    const combined = new Uint8Array(4 + bytes.length);
    combined.set(new Uint8Array(meta), 0);
    combined.set(bytes, 4);
    const payload = combined.buffer;
    worker.postMessage({ type: 'loadState', data: payload }, [payload]);
    canvasState = 'userModified';
  } catch { /* corrupt autosave, ignore */ }
}

// Activate default tool
selectTool(Tool.SAND);
updateBrushDisplay();

// Start with a random scene instead of a blank canvas
generateScene();
